### PR TITLE
fix: error when downloading the credential helper's latest version

### LINKED ISSUE #154: docker-credential-pass fails to download
### Orb version

2.0.3

### What happened

The [DOWNLOAD_URL](https://github.com/CircleCI-Public/docker-orb/blob/69fc0902686343a3bd14b2367e1dcb759cd92941/src/scripts/install-docker-credential-helper.sh#L62) is no longer valid for docker-credential-pass as it is now released as a binary at https://github.com/docker/docker-credential-helpers/releases/download/${RELEASE_VERSION}/${HELPER_FILENAME}-${RELEASE_VERSION}.(linux/darwin)-amd64 instead of being an archive at https://github.com/docker/docker-credential-helpers/releases/download/${RELEASE_VERSION}/${HELPER_FILENAME}-${RELEASE_VERSION}-amd64.tar.gz

  
### Expected behavior

docker-credential-helpers should be downloaded.

### PR DESCRIPTION
**Pull request by EricRibeiro**
### Checklist

- [x] All new jobs, commands, executors, parameters have descriptions
- [x] Examples have been added for any significant new features
- [x] README has been updated, if necessary

### Motivation, issues

Closes #154 

### Description

- Change the download URL based on the release's minor version.
- Add tests for release tags other than the latest

### CODE REVIEW

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/docker?version=dev:3050a67c0d499139fac03957e0ca5497f7527126

**Review by KyleTryon — APPROVED** [review]

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/docker?version=dev:83e2896b6cfc942c77e7828b5224123a7c512353

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/docker?version=dev:83e2896b6cfc942c77e7828b5224123a7c512353

**Comment by orb-publisher** [comment]
Your orb has been published to the CircleCI Orb Registry.
You can view your published orb on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/docker?version=2.1.4

File: src/scripts/install-docker-credential-helper.sh [hunk 1]
```diff
@@ -55,17 +58,28 @@ echo "Downloading credential helper $HELPER_FILENAME"
...
 if [ -n "${RELEASE_TAG}" ]; then
   RELEASE_VERSION="${RELEASE_TAG}"
 fi
-DOWNLOAD_URL="https://github.com/docker/docker-credential-helpers/releases/download/${RELEASE_VERSION}/${HELPER_FILENAME}-${RELEASE_VERSION}-amd64.tar.gz"
 
-echo "Downloading from url: $DOWNLOAD_URL"
-curl -L -o "${HELPER_FILENAME}_archive" "$DOWNLOAD_URL"
-tar xvf "./${HELPER_FILENAME}_archive"
-chmod +x "./$HELPER_FILENAME"
+# Starting from v0.7.0, the release file name is changed to docker-credential-<helper-name>-<os>-<arch>
```
Comment (crazy-max) [inline src/scripts/install-docker-credential-helper.sh:67]: Fyi, should be `docker-credential-<helper-name>-<os>-<arch><variant>`

Comment (bjohnso5) [reply src/scripts/install-docker-credential-helper.sh:67]: @EricRibeiro

Comment (EricRibeiro) [reply src/scripts/install-docker-credential-helper.sh:67]: @crazy-max, for my understanding, what would be the variant in the string below?

```
docker-credential-osxkeychain-v0.7.0.darwin-amd64
```

It looks like `docker-credential-<helper-name>-<version>.<os>-<arch>` 🤔

@bjohnso5, I believe they are referring to my comment. This shouldn't have any functional impact on the orb (if that is your concern).

Comment (crazy-max) [reply src/scripts/install-docker-credential-helper.sh:67]: This would refer for example to `arm` variants like `v6` and therefore would be `armv6` in filename.

There is also [`amd64` variants ](https://en.wikipedia.org/wiki/X86-64#Microarchitecture_levels) but we don't produce binaries for them atm (`v2`, `v3`, `v4`).

Comment (crazy-max) [reply src/scripts/install-docker-credential-helper.sh:67]: Not atm, this variant is really early. Will keep you posted anyway :+1:

Comment (EricRibeiro) [reply src/scripts/install-docker-credential-helper.sh:67]: I appreciate it. I'll update the comment to reflect your input.
